[tool.poetry]
name = "manage_fastapi"
version = "0.1.0"
description = ""
authors = ["Cristian Ordoñez <cristiano_ord93@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
